name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing Jupyter notebooks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: 'runtime.txt'

    - name: Install Python development requirements
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt

    - name: Run Python tests
      run: |
        python -m pytest --suppress-no-test-exit-code
